### Create a Product
POST http://localhost:4001/api/v1/stock
Content-Type: application/json

{
  "pincode": "500081",
  "name": "Amul High Protein Buttermilk, 200 mL | Pack of 30",
  "url": "https://shop.amul.com/en/product/amul-high-protein-buttermilk-200-ml-or-pack-of-30",
  "outOfStockSelector": "//div[contains(@class, 'alert-danger') and text()='Sold Out']",
  "isInStock": true,
  "lastChecked": "2025-06-21T10:30:00"
}

###